--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/CrossOnlineCount
projects:
  CrossOnlineCount:
    path: ""
    icon: icon.jpg
    libs:
      - src: jasonwynn10/libpmquery/libpmquery
        version: ^0.0.1
...